"""Advance Payment model modification

Revision ID: 0083030a72e7
Revises: ccb12be32e0e
Create Date: 2025-11-17 15:11:51.640230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0083030a72e7'
down_revision: Union[str, Sequence[str], None] = 'ccb12be32e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_advance_payments_payment_status'), table_name='marketline_advance_payments')
    op.drop_column('marketline_advance_payments', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_advance_payments', sa.Column('payment_status', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('ix_marketline_advance_payments_payment_status'), 'marketline_advance_payments', ['payment_status'], unique=False)
    # ### end Alembic commands ###
