"""updated the conficting issues in model & service

Revision ID: 07180a458d2f
Revises: 5ea5f3f61675
Create Date: 2025-09-23 18:37:12.654617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '07180a458d2f'
down_revision: Union[str, Sequence[str], None] = '5ea5f3f61675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
