"""origin & destination link up city

Revision ID: 0803f51b9961
Revises: 8ccebf785756
Create Date: 2025-10-08 18:14:32.394345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0803f51b9961'
down_revision: Union[str, Sequence[str], None] = '8ccebf785756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_vendors', sa.Column('origin_id', sa.Uuid(), nullable=True))
    op.add_column('marketline_vendors', sa.Column('destination_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'marketline_vendors', 'marketline_cities', ['origin_id'], ['id'])
    op.create_foreign_key(None, 'marketline_vendors', 'marketline_cities', ['destination_id'], ['id'])
    op.drop_column('marketline_vendors', 'origin')
    op.drop_column('marketline_vendors', 'destination')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_vendors', sa.Column('destination', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('marketline_vendors', sa.Column('origin', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'marketline_vendors', type_='foreignkey')
    op.drop_constraint(None, 'marketline_vendors', type_='foreignkey')
    op.drop_column('marketline_vendors', 'destination_id')
    op.drop_column('marketline_vendors', 'origin_id')
    # ### end Alembic commands ###
