"""enum updated for trip document

Revision ID: 1313c97f110c
Revises: 88b7f679d363
Create Date: 2025-11-04 11:57:32.991815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1313c97f110c'
down_revision: Union[str, Sequence[str], None] = '88b7f679d363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trip_documents', sa.Column('document_type', sa.Enum('LOADING', 'UNLOADING', name='vehicletypedocumentenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_trip_documents', 'document_type')
    # ### end Alembic commands ###
