"""add notifcations

Revision ID: 17a4169d4ec7
Revises: 4abc727451b0
Create Date: 2025-11-18 18:33:58.987880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '17a4169d4ec7'
down_revision: Union[str, Sequence[str], None] = '4abc727451b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('trip_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('trip_date', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['marketline_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_notifications_id'), 'marketline_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_notifications_is_active'), 'marketline_notifications', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_notifications_user_id'), 'marketline_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_notifications_user_id'), table_name='marketline_notifications')
    op.drop_index(op.f('ix_marketline_notifications_is_active'), table_name='marketline_notifications')
    op.drop_index(op.f('ix_marketline_notifications_id'), table_name='marketline_notifications')
    op.drop_table('marketline_notifications')
    # ### end Alembic commands ###
