"""vendor registration model name

Revision ID: 17e6b25637c8
Revises: 60e36444219d
Create Date: 2025-09-25 11:58:41.228567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '17e6b25637c8'
down_revision: Union[str, Sequence[str], None] = '60e36444219d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_vendor_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('transporter_firm_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('gst_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True,unique=True),
    sa.Column('gst_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pan_card_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True,unique=True),
    sa.Column('pan_card_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('pin_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('total_vehicle_owned', sa.Integer(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('visiting_card', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['marketline_regions.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_vendor_registrations_id'), 'marketline_vendor_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_vendor_registrations_is_active'), 'marketline_vendor_registrations', ['is_active'], unique=False)
    op.create_table('marketline_vendor_vehicle_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['marketline_vehicle_types.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendor_registrations.id'], ),
    sa.PrimaryKeyConstraint('id', 'vendor_id', 'vehicle_type_id')
    )
    op.create_index(op.f('ix_marketline_vendor_vehicle_type_id'), 'marketline_vendor_vehicle_type', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_vendor_vehicle_type_is_active'), 'marketline_vendor_vehicle_type', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_vendor_vehicle_type_is_active'), table_name='marketline_vendor_vehicle_type')
    op.drop_index(op.f('ix_marketline_vendor_vehicle_type_id'), table_name='marketline_vendor_vehicle_type')
    op.drop_table('marketline_vendor_vehicle_type')
    op.drop_index(op.f('ix_marketline_vendor_registrations_is_active'), table_name='marketline_vendor_registrations')
    op.drop_index(op.f('ix_marketline_vendor_registrations_id'), table_name='marketline_vendor_registrations')
    op.drop_table('marketline_vendor_registrations')
    # ### end Alembic commands ###
