"""init tables

Revision ID: 19cb4c232a7d
Revises: 
Create Date: 2025-09-21 22:39:37.410533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '19cb4c232a7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_permissions_id'), 'marketline_permissions', ['id'], unique=False)
    op.create_table('marketline_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_roles_id'), 'marketline_roles', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_roles_is_active'), 'marketline_roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_roles_name'), 'marketline_roles', ['name'], unique=True)
    op.create_table('marketline_role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['marketline_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['marketline_roles.id'], ),
    sa.PrimaryKeyConstraint('id', 'role_id', 'permission_id')
    )
    op.create_index(op.f('ix_marketline_role_permissions_id'), 'marketline_role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_role_permissions_is_active'), 'marketline_role_permissions', ['is_active'], unique=False)
    op.create_table('marketline_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['marketline_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_users_email'), 'marketline_users', ['email'], unique=True)
    op.create_index(op.f('ix_marketline_users_id'), 'marketline_users', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_users_is_active'), 'marketline_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_users_mobile'), 'marketline_users', ['mobile'], unique=True)
    op.create_index(op.f('ix_marketline_users_username'), 'marketline_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_users_username'), table_name='marketline_users')
    op.drop_index(op.f('ix_marketline_users_mobile'), table_name='marketline_users')
    op.drop_index(op.f('ix_marketline_users_is_active'), table_name='marketline_users')
    op.drop_index(op.f('ix_marketline_users_id'), table_name='marketline_users')
    op.drop_index(op.f('ix_marketline_users_email'), table_name='marketline_users')
    op.drop_table('marketline_users')
    op.drop_index(op.f('ix_marketline_role_permissions_is_active'), table_name='marketline_role_permissions')
    op.drop_index(op.f('ix_marketline_role_permissions_id'), table_name='marketline_role_permissions')
    op.drop_table('marketline_role_permissions')
    op.drop_index(op.f('ix_marketline_roles_name'), table_name='marketline_roles')
    op.drop_index(op.f('ix_marketline_roles_is_active'), table_name='marketline_roles')
    op.drop_index(op.f('ix_marketline_roles_id'), table_name='marketline_roles')
    op.drop_table('marketline_roles')
    op.drop_index(op.f('ix_marketline_permissions_id'), table_name='marketline_permissions')
    op.drop_table('marketline_permissions')
    # ### end Alembic commands ###
