"""trip model update

Revision ID: 1c2e4c6a9ac2
Revises: 3da11a07c0cd
Create Date: 2025-11-07 10:51:06.221753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1c2e4c6a9ac2'
down_revision: Union[str, Sequence[str], None] = '3da11a07c0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trips', sa.Column('is_balance_payment_approve', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_trips', 'is_balance_payment_approve')
    # ### end Alembic commands ###
