"""region added to employee model

Revision ID: 251647e1c7a4
Revises: 42dd669de5ae
Create Date: 2025-11-11 12:34:03.818494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '251647e1c7a4'
down_revision: Union[str, Sequence[str], None] = '42dd669de5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_employees', sa.Column('region_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'marketline_employees', 'marketline_regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketline_employees', type_='foreignkey')
    op.drop_column('marketline_employees', 'region_id')
    # ### end Alembic commands ###
