"""making field validations

Revision ID: 25a07ed30c9c
Revises: b3bb7fba1691
Create Date: 2025-10-08 12:39:20.045042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25a07ed30c9c'
down_revision: Union[str, Sequence[str], None] = 'b3bb7fba1691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_customers', 'gst_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('marketline_customers', 'pan_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_customers', 'pan_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('marketline_customers', 'gst_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
