"""Branch & employee

Revision ID: 26b5f4a81303
Revises: 6a16b575147a
Create Date: 2025-09-23 13:48:32.482527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '26b5f4a81303'
down_revision: Union[str, Sequence[str], None] = '6a16b575147a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('pin_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_marketline_branches_id'), 'marketline_branches', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_branches_is_active'), 'marketline_branches', ['is_active'], unique=False)
    op.create_table('marketline_employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('pin_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('employee_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('employee_pic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['marketline_branches.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['marketline_employees.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['marketline_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_employees_employee_code'), 'marketline_employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_marketline_employees_id'), 'marketline_employees', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_employees_is_active'), 'marketline_employees', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_employees_is_active'), table_name='marketline_employees')
    op.drop_index(op.f('ix_marketline_employees_id'), table_name='marketline_employees')
    op.drop_index(op.f('ix_marketline_employees_employee_code'), table_name='marketline_employees')
    op.drop_table('marketline_employees')
    op.drop_index(op.f('ix_marketline_branches_is_active'), table_name='marketline_branches')
    op.drop_index(op.f('ix_marketline_branches_id'), table_name='marketline_branches')
    op.drop_table('marketline_branches')
    # ### end Alembic commands ###
