"""remove notifcations fields

Revision ID: 28f9f36e8015
Revises: 17a4169d4ec7
Create Date: 2025-11-18 19:14:57.681134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '28f9f36e8015'
down_revision: Union[str, Sequence[str], None] = '17a4169d4ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_notifications', 'trip_id')
    op.drop_column('marketline_notifications', 'trip_date')
    op.drop_column('marketline_notifications', 'trip_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_notifications', sa.Column('trip_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('marketline_notifications', sa.Column('trip_date', mysql.DATETIME(), nullable=True))
    op.add_column('marketline_notifications', sa.Column('trip_id', mysql.CHAR(length=32), nullable=True))
    # ### end Alembic commands ###
