"""updated enum for vendor 

Revision ID: 2b5b5bc247d2
Revises: f8923e71b6cc
Create Date: 2025-09-26 13:48:38.497613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b5b5bc247d2'
down_revision: Union[str, Sequence[str], None] = 'f8923e71b6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_vendors', 'vendor_profile',
               existing_type=mysql.ENUM('BROKER', 'FLEET_OWNER'),
               nullable=True)
    op.alter_column('marketline_vendors', 'operation_zone',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('ALL_INDIA', 'ROUTE_SPECIFIC', name='operationzoneenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_vendors', 'operation_zone',
               existing_type=sa.Enum('ALL_INDIA', 'ROUTE_SPECIFIC', name='operationzoneenum'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('marketline_vendors', 'vendor_profile',
               existing_type=mysql.ENUM('BROKER', 'FLEET_OWNER'),
               nullable=False)
    # ### end Alembic commands ###
