"""approval history maintain

Revision ID: 2fbde5139d30
Revises: 452ea4128449
Create Date: 2025-12-11 13:02:55.607375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2fbde5139d30'
down_revision: Union[str, Sequence[str], None] = '452ea4128449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_payment_approval_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('approval_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['marketline_users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_payment_approval_history_approval_type'), 'marketline_payment_approval_history', ['approval_type'], unique=False)
    op.create_index(op.f('ix_marketline_payment_approval_history_id'), 'marketline_payment_approval_history', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_payment_approval_history_is_active'), 'marketline_payment_approval_history', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_payment_approval_history_is_active'), table_name='marketline_payment_approval_history')
    op.drop_index(op.f('ix_marketline_payment_approval_history_id'), table_name='marketline_payment_approval_history')
    op.drop_index(op.f('ix_marketline_payment_approval_history_approval_type'), table_name='marketline_payment_approval_history')
    op.drop_table('marketline_payment_approval_history')
    # ### end Alembic commands ###
