"""model update

Revision ID: 3da11a07c0cd
Revises: 34f1ab7811e3
Create Date: 2025-11-06 15:49:54.705608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3da11a07c0cd'
down_revision: Union[str, Sequence[str], None] = '34f1ab7811e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trips', sa.Column('is_advance_given', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_trips', 'is_advance_given')
    # ### end Alembic commands ###
