"""customer add

Revision ID: 3db1ecd96a4c
Revises: 3e2ce7bc2780
Create Date: 2025-10-07 16:30:35.568438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3db1ecd96a4c'
down_revision: Union[str, Sequence[str], None] = '3e2ce7bc2780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('customer_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('customer_type', sa.Enum('BROKING', 'BOOKING', name='customertypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='customerstatusenum'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('gst_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('gst_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pan_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('pan_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('pin_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('address_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address_document_type', sa.Enum('AADHAR_CARD', 'VOTER_CARD', 'VISITING_CARD', 'DRIVING_LICENSE', name='addressdocumenttype'), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=True),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('tonnage', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('trip_rate', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('credit_period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['marketline_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code'),
    sa.UniqueConstraint('gst_number'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_index(op.f('ix_marketline_customers_id'), 'marketline_customers', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_customers_is_active'), 'marketline_customers', ['is_active'], unique=False)
    op.create_table('marketline_customer_agreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['marketline_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_customer_agreements_id'), 'marketline_customer_agreements', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_customer_agreements_is_active'), 'marketline_customer_agreements', ['is_active'], unique=False)
    op.create_table('marketline_customer_contact_persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['marketline_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_marketline_customer_contact_persons_id'), 'marketline_customer_contact_persons', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_customer_contact_persons_is_active'), 'marketline_customer_contact_persons', ['is_active'], unique=False)
    op.create_table('marketline_customer_vehicle_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['marketline_customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['marketline_vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'vehicle_type_id')
    )
    op.create_index(op.f('ix_marketline_customer_vehicle_link_id'), 'marketline_customer_vehicle_link', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_customer_vehicle_link_is_active'), 'marketline_customer_vehicle_link', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_customer_vehicle_link_is_active'), table_name='marketline_customer_vehicle_link')
    op.drop_index(op.f('ix_marketline_customer_vehicle_link_id'), table_name='marketline_customer_vehicle_link')
    op.drop_table('marketline_customer_vehicle_link')
    op.drop_index(op.f('ix_marketline_customer_contact_persons_is_active'), table_name='marketline_customer_contact_persons')
    op.drop_index(op.f('ix_marketline_customer_contact_persons_id'), table_name='marketline_customer_contact_persons')
    op.drop_table('marketline_customer_contact_persons')
    op.drop_index(op.f('ix_marketline_customer_agreements_is_active'), table_name='marketline_customer_agreements')
    op.drop_index(op.f('ix_marketline_customer_agreements_id'), table_name='marketline_customer_agreements')
    op.drop_table('marketline_customer_agreements')
    op.drop_index(op.f('ix_marketline_customers_is_active'), table_name='marketline_customers')
    op.drop_index(op.f('ix_marketline_customers_id'), table_name='marketline_customers')
    op.drop_table('marketline_customers')
    # ### end Alembic commands ###
