"""add target module

Revision ID: 3db48b8af89d
Revises: d415f8f1d8ab
Create Date: 2025-10-23 17:39:58.196521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3db48b8af89d'
down_revision: Union[str, Sequence[str], None] = 'd415f8f1d8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('no_of_trip', sa.Integer(), nullable=False),
    sa.Column('total_margin', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CLOSED', name='targetstatusenum'), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('achieved_trips', sa.Integer(), nullable=False),
    sa.Column('achieved_margin', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('achieved_revenue', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['marketline_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_targets_id'), 'marketline_targets', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_targets_is_active'), 'marketline_targets', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_targets_is_active'), table_name='marketline_targets')
    op.drop_index(op.f('ix_marketline_targets_id'), table_name='marketline_targets')
    op.drop_table('marketline_targets')
    # ### end Alembic commands ###
