"""add status enum in registration

Revision ID: 3e2ce7bc2780
Revises: 95a0e9b3796d
Create Date: 2025-10-06 13:12:22.594236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3e2ce7bc2780'
down_revision: Union[str, Sequence[str], None] = '95a0e9b3796d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_vendor_registrations', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='vendorregistrationstatusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_vendor_registrations', 'status')
    # ### end Alembic commands ###
