"""introducing reject reason

Revision ID: 44183ab2e153
Revises: 25a07ed30c9c
Create Date: 2025-10-08 13:21:50.296673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '44183ab2e153'
down_revision: Union[str, Sequence[str], None] = '25a07ed30c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_customers', sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_customers', 'reject_reason')
    # ### end Alembic commands ###
