"""add mobile email password to customer

Revision ID: 452ea4128449
Revises: a35751a61809
Create Date: 2025-12-03 17:32:17.391441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '452ea4128449'
down_revision: Union[str, Sequence[str], None] = 'a35751a61809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_customers', sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('marketline_customers', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('marketline_customers', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_customers', 'password')
    op.drop_column('marketline_customers', 'email')
    op.drop_column('marketline_customers', 'mobile')
    # ### end Alembic commands ###
