"""remove duplicate fields & cancel reason

Revision ID: 4a96ec48dc86
Revises: 572bb7bbea9c
Create Date: 2025-10-09 18:51:43.758688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a96ec48dc86'
down_revision: Union[str, Sequence[str], None] = '572bb7bbea9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trips', sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.drop_column('marketline_trips', 'actual_tat_hours')
    op.drop_column('marketline_trips', 'other_remarks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trips', sa.Column('other_remarks', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('marketline_trips', sa.Column('actual_tat_hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('marketline_trips', 'cancellation_reason')
    # ### end Alembic commands ###
