"""Payment date can be null

Revision ID: 4abc727451b0
Revises: 0083030a72e7
Create Date: 2025-11-17 15:25:20.294887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '4abc727451b0'
down_revision: Union[str, Sequence[str], None] = '0083030a72e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_advance_payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_advance_payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
