"""trip model update

Revision ID: 4ff51260330b
Revises: 81762b88e6cc
Create Date: 2025-11-05 13:03:03.507531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ff51260330b'
down_revision: Union[str, Sequence[str], None] = '81762b88e6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_trip_status_history', 'previous_status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', 'VEHICLE_LOADED', 'VEHICLE_UNLOADED', 'FLIT_RATE_APPROVE', 'FLIT_RATE_REJECT', 'ADVANCE_PAYMENT_PENDING', 'ADVANCE_PAYMENT_APPROVED', 'ADVANCE_PAYMENT_REJECTED', name='tripstatusenum', native_enum=False, length=100),
               existing_nullable=True)
    op.alter_column('marketline_trip_status_history', 'current_status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', 'VEHICLE_LOADED', 'VEHICLE_UNLOADED', 'FLIT_RATE_APPROVE', 'FLIT_RATE_REJECT', 'ADVANCE_PAYMENT_PENDING', 'ADVANCE_PAYMENT_APPROVED', 'ADVANCE_PAYMENT_REJECTED', name='tripstatusenum', native_enum=False, length=100),
               existing_nullable=False)
    op.add_column('marketline_trips', sa.Column('is_advance_payment_done', sa.Boolean(), nullable=True))
    op.alter_column('marketline_trips', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', 'VEHICLE_LOADED', 'VEHICLE_UNLOADED', 'FLIT_RATE_APPROVE', 'FLIT_RATE_REJECT', 'ADVANCE_PAYMENT_PENDING', 'ADVANCE_PAYMENT_APPROVED', 'ADVANCE_PAYMENT_REJECTED', name='tripstatusenum', native_enum=False, length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_trips', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', 'VEHICLE_LOADED', 'VEHICLE_UNLOADED', 'FLIT_RATE_APPROVE', 'FLIT_RATE_REJECT', 'ADVANCE_PAYMENT_PENDING', 'ADVANCE_PAYMENT_APPROVED', 'ADVANCE_PAYMENT_REJECTED', name='tripstatusenum', native_enum=False, length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('marketline_trips', 'is_advance_payment_done')
    op.alter_column('marketline_trip_status_history', 'current_status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', 'VEHICLE_LOADED', 'VEHICLE_UNLOADED', 'FLIT_RATE_APPROVE', 'FLIT_RATE_REJECT', 'ADVANCE_PAYMENT_PENDING', 'ADVANCE_PAYMENT_APPROVED', 'ADVANCE_PAYMENT_REJECTED', name='tripstatusenum', native_enum=False, length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('marketline_trip_status_history', 'previous_status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', 'VEHICLE_LOADED', 'VEHICLE_UNLOADED', 'FLIT_RATE_APPROVE', 'FLIT_RATE_REJECT', 'ADVANCE_PAYMENT_PENDING', 'ADVANCE_PAYMENT_APPROVED', 'ADVANCE_PAYMENT_REJECTED', name='tripstatusenum', native_enum=False, length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
