"""modify & table relation updates

Revision ID: 572bb7bbea9c
Revises: 578054cb4420
Create Date: 2025-10-09 16:57:28.469449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '572bb7bbea9c'
down_revision: Union[str, Sequence[str], None] = '578054cb4420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trips', sa.Column('customer_trip_id', sa.Uuid(), nullable=True))
    op.alter_column('marketline_trips', 'vehicle_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('marketline_trips', 'tonnage',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('marketline_trips', 'vehicle_type_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.alter_column('marketline_trips', 'driver_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('marketline_trips', 'dl_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('marketline_trips', 'dl_expiry_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('marketline_trips', 'driver_mobile',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_foreign_key(None, 'marketline_trips', 'marketline_trips', ['customer_trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketline_trips', type_='foreignkey')
    op.alter_column('marketline_trips', 'driver_mobile',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('marketline_trips', 'dl_expiry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('marketline_trips', 'dl_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('marketline_trips', 'driver_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('marketline_trips', 'vehicle_type_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.alter_column('marketline_trips', 'tonnage',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('marketline_trips', 'vehicle_no',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('marketline_trips', 'customer_trip_id')
    # ### end Alembic commands ###
