"""Add trip model with origins and destinations

Revision ID: 578054cb4420
Revises: 0803f51b9961
Create Date: 2025-10-09 15:42:56.011105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '578054cb4420'
down_revision: Union[str, Sequence[str], None] = '0803f51b9961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('trip_type', sa.Enum('VENDOR', 'CUSTOMER', name='triptypeenum'), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatusenum'), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('lane', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('vehicle_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tonnage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('vehicle_type_id', sa.Uuid(), nullable=False),
    sa.Column('rc_upload', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('insurance', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('driver_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('dl_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('dl_expiry_date', sa.Date(), nullable=False),
    sa.Column('driver_mobile', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('trip_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('detention_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loading_unloading_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bill_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loading_slip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tat_hours', sa.Integer(), nullable=True),
    sa.Column('actual_tat_hours', sa.Integer(), nullable=True),
    sa.Column('other_remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['marketline_branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['marketline_customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['marketline_vehicle_types.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_trips_id'), 'marketline_trips', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trips_is_active'), 'marketline_trips', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_trips_trip_code'), 'marketline_trips', ['trip_code'], unique=True)
    op.create_table('marketline_trip_destinations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.PrimaryKeyConstraint('id', 'trip_id', 'city_id')
    )
    op.create_index(op.f('ix_marketline_trip_destinations_id'), 'marketline_trip_destinations', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_destinations_is_active'), 'marketline_trip_destinations', ['is_active'], unique=False)
    op.create_table('marketline_trip_origins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.PrimaryKeyConstraint('id', 'trip_id', 'city_id')
    )
    op.create_index(op.f('ix_marketline_trip_origins_id'), 'marketline_trip_origins', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_origins_is_active'), 'marketline_trip_origins', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_trip_origins_is_active'), table_name='marketline_trip_origins')
    op.drop_index(op.f('ix_marketline_trip_origins_id'), table_name='marketline_trip_origins')
    op.drop_table('marketline_trip_origins')
    op.drop_index(op.f('ix_marketline_trip_destinations_is_active'), table_name='marketline_trip_destinations')
    op.drop_index(op.f('ix_marketline_trip_destinations_id'), table_name='marketline_trip_destinations')
    op.drop_table('marketline_trip_destinations')
    op.drop_index(op.f('ix_marketline_trips_trip_code'), table_name='marketline_trips')
    op.drop_index(op.f('ix_marketline_trips_is_active'), table_name='marketline_trips')
    op.drop_index(op.f('ix_marketline_trips_id'), table_name='marketline_trips')
    op.drop_table('marketline_trips')
    # ### end Alembic commands ###
