"""trip updates apply

Revision ID: 587021a82156
Revises: c88967d0598b
Create Date: 2025-10-27 19:17:20.450902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '587021a82156'
down_revision: Union[str, Sequence[str], None] = 'c88967d0598b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_trip_loading_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_trip_loading_addresses_id'), 'marketline_trip_loading_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_loading_addresses_is_active'), 'marketline_trip_loading_addresses', ['is_active'], unique=False)
    op.create_table('marketline_trip_unloading_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_trip_unloading_addresses_id'), 'marketline_trip_unloading_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_unloading_addresses_is_active'), 'marketline_trip_unloading_addresses', ['is_active'], unique=False)
    op.drop_index(op.f('ix_marketline_trip_destinations_id'), table_name='marketline_trip_destinations')
    op.drop_index(op.f('ix_marketline_trip_destinations_is_active'), table_name='marketline_trip_destinations')
    op.drop_table('marketline_trip_destinations')
    op.drop_index(op.f('ix_marketline_trip_origins_id'), table_name='marketline_trip_origins')
    op.drop_index(op.f('ix_marketline_trip_origins_is_active'), table_name='marketline_trip_origins')
    op.drop_table('marketline_trip_origins')
    op.add_column('marketline_trips', sa.Column('capacity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('marketline_trips', sa.Column('goods_type', sa.Enum('FMCG', 'CHEMICAL', 'FASHION', 'ELECTRONICS', 'OTHER', name='goodstypeenum'), nullable=False))
    op.add_column('marketline_trips', sa.Column('goods_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('marketline_trips', sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.alter_column('marketline_trips', 'customer_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.alter_column('marketline_trips', 'vehicle_type_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.drop_constraint(op.f('marketline_trips_ibfk_4'), 'marketline_trips', type_='foreignkey')
    op.drop_constraint(op.f('marketline_trips_ibfk_5'), 'marketline_trips', type_='foreignkey')
    op.drop_column('marketline_trips', 'dl_no')
    op.drop_column('marketline_trips', 'vendor_id')
    op.drop_column('marketline_trips', 'tat_hours')
    op.drop_column('marketline_trips', 'other_charges')
    op.drop_column('marketline_trips', 'tonnage')
    op.drop_column('marketline_trips', 'driver_mobile')
    op.drop_column('marketline_trips', 'customer_trip_id')
    op.drop_column('marketline_trips', 'lane')
    op.drop_column('marketline_trips', 'bill_charge')
    op.drop_column('marketline_trips', 'driver_name')
    op.drop_column('marketline_trips', 'loading_slip')
    op.drop_column('marketline_trips', 'insurance')
    op.drop_column('marketline_trips', 'trip_type')
    op.drop_column('marketline_trips', 'dl_expiry_date')
    op.drop_column('marketline_trips', 'insurance_expiry_date')
    op.drop_column('marketline_trips', 'rc_upload')
    op.drop_column('marketline_trips', 'vehicle_no')
    op.drop_column('marketline_trips', 'detention_rate')
    op.drop_column('marketline_trips', 'remarks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trips', sa.Column('remarks', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('marketline_trips', sa.Column('detention_rate', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('marketline_trips', sa.Column('vehicle_no', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('marketline_trips', sa.Column('rc_upload', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('marketline_trips', sa.Column('insurance_expiry_date', sa.DATE(), nullable=True))
    op.add_column('marketline_trips', sa.Column('dl_expiry_date', sa.DATE(), nullable=True))
    op.add_column('marketline_trips', sa.Column('trip_type', mysql.ENUM('VENDOR', 'CUSTOMER'), nullable=False))
    op.add_column('marketline_trips', sa.Column('insurance', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('marketline_trips', sa.Column('loading_slip', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('marketline_trips', sa.Column('driver_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('marketline_trips', sa.Column('bill_charge', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('marketline_trips', sa.Column('lane', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('marketline_trips', sa.Column('customer_trip_id', mysql.CHAR(length=32), nullable=True))
    op.add_column('marketline_trips', sa.Column('driver_mobile', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('marketline_trips', sa.Column('tonnage', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('marketline_trips', sa.Column('other_charges', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('marketline_trips', sa.Column('tat_hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('marketline_trips', sa.Column('vendor_id', mysql.CHAR(length=32), nullable=True))
    op.add_column('marketline_trips', sa.Column('dl_no', mysql.VARCHAR(length=50), nullable=True))
    op.create_foreign_key(op.f('marketline_trips_ibfk_5'), 'marketline_trips', 'marketline_trips', ['customer_trip_id'], ['id'])
    op.create_foreign_key(op.f('marketline_trips_ibfk_4'), 'marketline_trips', 'marketline_vendors', ['vendor_id'], ['id'])
    op.alter_column('marketline_trips', 'vehicle_type_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.alter_column('marketline_trips', 'customer_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.drop_column('marketline_trips', 'instructions')
    op.drop_column('marketline_trips', 'goods_name')
    op.drop_column('marketline_trips', 'goods_type')
    op.drop_column('marketline_trips', 'capacity')
    op.create_table('marketline_trip_origins',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('trip_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('city_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('sequence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], name=op.f('marketline_trip_origins_ibfk_1')),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], name=op.f('marketline_trip_origins_ibfk_2')),
    sa.PrimaryKeyConstraint('id', 'trip_id', 'city_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_marketline_trip_origins_is_active'), 'marketline_trip_origins', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_trip_origins_id'), 'marketline_trip_origins', ['id'], unique=False)
    op.create_table('marketline_trip_destinations',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('trip_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('city_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('sequence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], name=op.f('marketline_trip_destinations_ibfk_1')),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], name=op.f('marketline_trip_destinations_ibfk_2')),
    sa.PrimaryKeyConstraint('id', 'trip_id', 'city_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_marketline_trip_destinations_is_active'), 'marketline_trip_destinations', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_trip_destinations_id'), 'marketline_trip_destinations', ['id'], unique=False)
    op.drop_index(op.f('ix_marketline_trip_unloading_addresses_is_active'), table_name='marketline_trip_unloading_addresses')
    op.drop_index(op.f('ix_marketline_trip_unloading_addresses_id'), table_name='marketline_trip_unloading_addresses')
    op.drop_table('marketline_trip_unloading_addresses')
    op.drop_index(op.f('ix_marketline_trip_loading_addresses_is_active'), table_name='marketline_trip_loading_addresses')
    op.drop_index(op.f('ix_marketline_trip_loading_addresses_id'), table_name='marketline_trip_loading_addresses')
    op.drop_table('marketline_trip_loading_addresses')
    # ### end Alembic commands ###
