"""trip address module work

Revision ID: 589a346b08df
Revises: 1ade47651d6f
Create Date: 2025-10-30 11:38:24.453107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '589a346b08df'
down_revision: Union[str, Sequence[str], None] = '1ade47651d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_trip_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('address_type', sa.Enum('LOADING', 'UNLOADING', name='addresstypeenum'), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_trip_addresses_id'), 'marketline_trip_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_addresses_is_active'), 'marketline_trip_addresses', ['is_active'], unique=False)
    op.drop_index(op.f('ix_marketline_trip_loading_addresses_id'), table_name='marketline_trip_loading_addresses')
    op.drop_index(op.f('ix_marketline_trip_loading_addresses_is_active'), table_name='marketline_trip_loading_addresses')
    op.drop_table('marketline_trip_loading_addresses')
    op.drop_index(op.f('ix_marketline_trip_unloading_addresses_id'), table_name='marketline_trip_unloading_addresses')
    op.drop_index(op.f('ix_marketline_trip_unloading_addresses_is_active'), table_name='marketline_trip_unloading_addresses')
    op.drop_table('marketline_trip_unloading_addresses')
    op.alter_column('marketline_complaints', 'status',
               existing_type=mysql.ENUM('OPEN', 'INPROGRESS', 'RESOLVED'),
               type_=sa.Enum('OPEN', 'INPROGRESS', 'CLOSED', name='complaintstatusenum'),
               existing_nullable=False)
    op.alter_column('marketline_trips', 'capacity',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_trips', 'capacity',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('marketline_complaints', 'status',
               existing_type=sa.Enum('OPEN', 'INPROGRESS', 'CLOSED', name='complaintstatusenum'),
               type_=mysql.ENUM('OPEN', 'INPROGRESS', 'RESOLVED'),
               existing_nullable=False)
    op.create_table('marketline_trip_unloading_addresses',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('trip_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('country_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('state_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('district_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('city_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('pincode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('sequence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], name=op.f('marketline_trip_unloading_addresses_ibfk_1')),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], name=op.f('marketline_trip_unloading_addresses_ibfk_2')),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], name=op.f('marketline_trip_unloading_addresses_ibfk_3')),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], name=op.f('marketline_trip_unloading_addresses_ibfk_4')),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], name=op.f('marketline_trip_unloading_addresses_ibfk_5')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_marketline_trip_unloading_addresses_is_active'), 'marketline_trip_unloading_addresses', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_trip_unloading_addresses_id'), 'marketline_trip_unloading_addresses', ['id'], unique=False)
    op.create_table('marketline_trip_loading_addresses',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('trip_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('country_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('state_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('district_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('city_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('pincode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('sequence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], name=op.f('marketline_trip_loading_addresses_ibfk_1')),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], name=op.f('marketline_trip_loading_addresses_ibfk_2')),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], name=op.f('marketline_trip_loading_addresses_ibfk_3')),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], name=op.f('marketline_trip_loading_addresses_ibfk_4')),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], name=op.f('marketline_trip_loading_addresses_ibfk_5')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_marketline_trip_loading_addresses_is_active'), 'marketline_trip_loading_addresses', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_trip_loading_addresses_id'), 'marketline_trip_loading_addresses', ['id'], unique=False)
    op.drop_index(op.f('ix_marketline_trip_addresses_is_active'), table_name='marketline_trip_addresses')
    op.drop_index(op.f('ix_marketline_trip_addresses_id'), table_name='marketline_trip_addresses')
    op.drop_table('marketline_trip_addresses')
    # ### end Alembic commands ###
