"""Branch name unique & employee optional fields

Revision ID: 5ea5f3f61675
Revises: 26b5f4a81303
Create Date: 2025-09-23 15:43:00.428598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ea5f3f61675'
down_revision: Union[str, Sequence[str], None] = '26b5f4a81303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'marketline_branches', ['name'])
    op.alter_column('marketline_employees', 'branch_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.alter_column('marketline_employees', 'manager_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_employees', 'manager_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.alter_column('marketline_employees', 'branch_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.drop_constraint(None, 'marketline_branches', type_='unique')
    # ### end Alembic commands ###
