"""add desc string

Revision ID: 61208a83eaa7
Revises: 5bbb95900f5f
Create Date: 2025-11-18 17:26:54.945875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61208a83eaa7'
down_revision: Union[str, Sequence[str], None] = '5bbb95900f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_emails', 'failed_reason')
    op.drop_column('marketline_emails', 'sent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_emails', sa.Column('sent_at', mysql.DATETIME(), nullable=True))
    op.add_column('marketline_emails', sa.Column('failed_reason', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
