"""Trip document model add

Revision ID: 69340318a98a
Revises: 1f25fc9d94ac
Create Date: 2025-11-03 18:26:09.365521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '69340318a98a'
down_revision: Union[str, Sequence[str], None] = '1f25fc9d94ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_trip_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('eway_bill', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('invoice_copy', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vehicle_image', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('lr_copy', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('pod_submitted', sa.Boolean(), nullable=True),
    sa.Column('other_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_shortage', sa.Boolean(), nullable=True),
    sa.Column('is_damage', sa.Boolean(), nullable=True),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('deducted_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deducted_details', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_trip_documents_id'), 'marketline_trip_documents', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_documents_is_active'), 'marketline_trip_documents', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_trip_documents_is_active'), table_name='marketline_trip_documents')
    op.drop_index(op.f('ix_marketline_trip_documents_id'), table_name='marketline_trip_documents')
    op.drop_table('marketline_trip_documents')
    # ### end Alembic commands ###
