"""table relation changes

Revision ID: 6a16b575147a
Revises: 19cb4c232a7d
Create Date: 2025-09-22 18:33:52.473187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '6a16b575147a'
down_revision: Union[str, Sequence[str], None] = '19cb4c232a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_countries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketline_countries_id'), 'marketline_countries', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_countries_is_active'), 'marketline_countries', ['is_active'], unique=False)
    op.create_table('marketline_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketline_states_id'), 'marketline_states', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_states_is_active'), 'marketline_states', ['is_active'], unique=False)
    op.create_table('marketline_districts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketline_districts_id'), 'marketline_districts', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_districts_is_active'), 'marketline_districts', ['is_active'], unique=False)
    op.create_table('marketline_cities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketline_cities_id'), 'marketline_cities', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_cities_is_active'), 'marketline_cities', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_cities_is_active'), table_name='marketline_cities')
    op.drop_index(op.f('ix_marketline_cities_id'), table_name='marketline_cities')
    op.drop_table('marketline_cities')
    op.drop_index(op.f('ix_marketline_districts_is_active'), table_name='marketline_districts')
    op.drop_index(op.f('ix_marketline_districts_id'), table_name='marketline_districts')
    op.drop_table('marketline_districts')
    op.drop_index(op.f('ix_marketline_states_is_active'), table_name='marketline_states')
    op.drop_index(op.f('ix_marketline_states_id'), table_name='marketline_states')
    op.drop_table('marketline_states')
    op.drop_index(op.f('ix_marketline_countries_is_active'), table_name='marketline_countries')
    op.drop_index(op.f('ix_marketline_countries_id'), table_name='marketline_countries')
    op.drop_table('marketline_countries')
    # ### end Alembic commands ###
