"""Trip driver model added

Revision ID: 6e93a07d2527
Revises: cfde69d81f08
Create Date: 2025-11-03 11:52:31.257296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e93a07d2527'
down_revision: Union[str, Sequence[str], None] = 'cfde69d81f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_trip_drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_vendor_id', sa.Uuid(), nullable=False),
    sa.Column('driver_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('driver_mobile_no', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('driver_licence_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('driver_licence_expiry', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['trip_vendor_id'], ['marketline_trip_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_trip_drivers_id'), 'marketline_trip_drivers', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_drivers_is_active'), 'marketline_trip_drivers', ['is_active'], unique=False)
    op.alter_column('marketline_trip_vendors', 'insurance_expiry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('marketline_trip_vendors', 'driver_licence_no')
    op.drop_column('marketline_trip_vendors', 'driver_licence_expiry')
    op.drop_column('marketline_trip_vendors', 'driver_name')
    op.drop_column('marketline_trip_vendors', 'driver_mobile_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trip_vendors', sa.Column('driver_mobile_no', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('marketline_trip_vendors', sa.Column('driver_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('marketline_trip_vendors', sa.Column('driver_licence_expiry', sa.DATE(), nullable=False))
    op.add_column('marketline_trip_vendors', sa.Column('driver_licence_no', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('marketline_trip_vendors', 'insurance_expiry_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_marketline_trip_drivers_is_active'), table_name='marketline_trip_drivers')
    op.drop_index(op.f('ix_marketline_trip_drivers_id'), table_name='marketline_trip_drivers')
    op.drop_table('marketline_trip_drivers')
    # ### end Alembic commands ###
