"""notification model updated

Revision ID: 772392c1b3a2
Revises: 98bdf7d87846
Create Date: 2026-02-02 15:29:02.369663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '772392c1b3a2'
down_revision: Union[str, Sequence[str], None] = '98bdf7d87846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_notifications', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('marketline_notifications', sa.Column('action_required', sa.Boolean(), nullable=False))
    op.add_column('marketline_notifications', sa.Column('action_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('marketline_notifications', sa.Column('action_deadline', sa.DateTime(), nullable=True))
    op.alter_column('marketline_notifications', 'user_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_notifications', 'user_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.drop_column('marketline_notifications', 'action_deadline')
    op.drop_column('marketline_notifications', 'action_data')
    op.drop_column('marketline_notifications', 'action_required')
    op.drop_column('marketline_notifications', 'role')
    # ### end Alembic commands ###
