"""model update

Revision ID: 81762b88e6cc
Revises: 9ac9b620eb74
Create Date: 2025-11-04 13:31:32.312222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81762b88e6cc'
down_revision: Union[str, Sequence[str], None] = '9ac9b620eb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trip_documents', sa.Column('pod_submit', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('marketline_trip_documents', 'pod_submitted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trip_documents', sa.Column('pod_submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('marketline_trip_documents', 'pod_submit')
    # ### end Alembic commands ###
