"""add desc string

Revision ID: 86c35fa1acb3
Revises: 329fc5a1af19
Create Date: 2026-01-21 14:29:16.999769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '86c35fa1acb3'
down_revision: Union[str, Sequence[str], None] = '329fc5a1af19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_advance_payments', sa.Column('is_payment_due', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_advance_payments', 'is_payment_due')
    # ### end Alembic commands ###
