"""add deduct amount

Revision ID: 88d3490f0085
Revises: 2fbde5139d30
Create Date: 2025-12-11 17:34:21.085484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '88d3490f0085'
down_revision: Union[str, Sequence[str], None] = '2fbde5139d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_advance_payments', sa.Column('is_deduct_amount', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_advance_payments', 'is_deduct_amount')
    # ### end Alembic commands ###
