"""trip vendor model add

Revision ID: 88db81d3e581
Revises: 73db0197f5df
Create Date: 2025-10-31 15:21:17.763403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '88db81d3e581'
down_revision: Union[str, Sequence[str], None] = '73db0197f5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_trip_vendors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_type_id', sa.Uuid(), nullable=False),
    sa.Column('tons', sa.Integer(), nullable=False),
    sa.Column('vehicle_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('rc_copy', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('insurance_copy', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('driver_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('driver_mobile_no', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('driver_licence_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('driver_licence_expiry', sa.Date(), nullable=False),
    sa.Column('trip_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['marketline_branches.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['marketline_vehicle_types.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_trip_vendors_id'), 'marketline_trip_vendors', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_vendors_is_active'), 'marketline_trip_vendors', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_trip_vendors_is_active'), table_name='marketline_trip_vendors')
    op.drop_index(op.f('ix_marketline_trip_vendors_id'), table_name='marketline_trip_vendors')
    op.drop_table('marketline_trip_vendors')
    # ### end Alembic commands ###
