"""Add reject_reason and agreement_document to vendors

Revision ID: 8ccebf785756
Revises: 44183ab2e153
Create Date: 2025-10-08 14:59:03.392390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8ccebf785756'
down_revision: Union[str, Sequence[str], None] = '44183ab2e153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_vendor_agreements', sa.Column('agreement_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('marketline_vendors', sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_vendors', 'reject_reason')
    op.drop_column('marketline_vendor_agreements', 'agreement_document')
    # ### end Alembic commands ###
