"""vehicle type add

Revision ID: 8dc621676999
Revises: 07180a458d2f
Create Date: 2025-09-24 17:11:43.344106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8dc621676999'
down_revision: Union[str, Sequence[str], None] = '07180a458d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_vehicle_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketline_vehicle_types_id'), 'marketline_vehicle_types', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_vehicle_types_is_active'), 'marketline_vehicle_types', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_vehicle_types_is_active'), table_name='marketline_vehicle_types')
    op.drop_index(op.f('ix_marketline_vehicle_types_id'), table_name='marketline_vehicle_types')
    op.drop_table('marketline_vehicle_types')
    # ### end Alembic commands ###
