"""trip history module add

Revision ID: 950d57358b17
Revises: 589a346b08df
Create Date: 2025-10-30 13:41:16.282692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '950d57358b17'
down_revision: Union[str, Sequence[str], None] = '589a346b08df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_trip_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatusenum'), nullable=True),
    sa.Column('current_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatusenum'), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_trip_status_history_id'), 'marketline_trip_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_trip_status_history_is_active'), 'marketline_trip_status_history', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_trip_status_history_is_active'), table_name='marketline_trip_status_history')
    op.drop_index(op.f('ix_marketline_trip_status_history_id'), table_name='marketline_trip_status_history')
    op.drop_table('marketline_trip_status_history')
    # ### end Alembic commands ###
