"""Advance Payment model modification

Revision ID: 970ac94ddb89
Revises: d7779b09d060
Create Date: 2025-11-17 13:37:30.996085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '970ac94ddb89'
down_revision: Union[str, Sequence[str], None] = 'd7779b09d060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_advance_payments', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.create_index(op.f('ix_marketline_advance_payments_payment_status'), 'marketline_advance_payments', ['payment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_advance_payments_payment_status'), table_name='marketline_advance_payments')
    op.drop_column('marketline_advance_payments', 'payment_status')
    # ### end Alembic commands ###
