"""contact persons unique false

Revision ID: 98e40f276ff0
Revises: db873655a2ee
Create Date: 2025-10-13 12:06:59.652411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '98e40f276ff0'
down_revision: Union[str, Sequence[str], None] = 'db873655a2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='marketline_customer_contact_persons')
    op.drop_index(op.f('email'), table_name='marketline_vendor_contact_persons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email'), 'marketline_vendor_contact_persons', ['email'], unique=True)
    op.create_index(op.f('email'), 'marketline_customer_contact_persons', ['email'], unique=True)
    # ### end Alembic commands ###
