"""enum updated for trip document

Revision ID: 9ac9b620eb74
Revises: 1313c97f110c
Create Date: 2025-11-04 13:21:50.930824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ac9b620eb74'
down_revision: Union[str, Sequence[str], None] = '1313c97f110c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_trip_documents', 'document_type')
    op.drop_column('marketline_trip_documents', 'other_charges')
    op.drop_column('marketline_trip_documents', 'is_shortage')
    op.drop_column('marketline_trip_documents', 'is_damage')
    op.drop_column('marketline_trip_documents', 'deducted_amount')
    op.drop_column('marketline_trip_documents', 'deducted_details')
    op.add_column('marketline_trip_vendors', sa.Column('other_unloading_charges', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('marketline_trips', sa.Column('is_shortage', sa.Boolean(), nullable=True))
    op.add_column('marketline_trips', sa.Column('is_damage', sa.Boolean(), nullable=True))
    op.add_column('marketline_trips', sa.Column('deducted_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('marketline_trips', sa.Column('deducted_details', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_trips', 'deducted_details')
    op.drop_column('marketline_trips', 'deducted_amount')
    op.drop_column('marketline_trips', 'is_damage')
    op.drop_column('marketline_trips', 'is_shortage')
    op.drop_column('marketline_trip_vendors', 'other_unloading_charges')
    op.add_column('marketline_trip_documents', sa.Column('deducted_details', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('marketline_trip_documents', sa.Column('deducted_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('marketline_trip_documents', sa.Column('is_damage', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('marketline_trip_documents', sa.Column('is_shortage', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('marketline_trip_documents', sa.Column('other_charges', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('marketline_trip_documents', sa.Column('document_type', mysql.ENUM('LOADING', 'UNLOADING'), nullable=False))
    # ### end Alembic commands ###
