"""add check customer

Revision ID: abf9b1d27eee
Revises: 8c2c14d2d866
Create Date: 2025-11-05 19:45:00.509555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'abf9b1d27eee'
down_revision: Union[str, Sequence[str], None] = '8c2c14d2d866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trips', sa.Column('pod_sent_to_customer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_trips', 'pod_sent_to_customer')
    # ### end Alembic commands ###
