"""add_vendor_tables

Revision ID: b29c1584c4b4
Revises: 17e6b25637c8
Create Date: 2025-09-25 17:01:29.719898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b29c1584c4b4'
down_revision: Union[str, Sequence[str], None] = '17e6b25637c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_vendors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('vendor_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_type', sa.Enum('CREDIT_VENDOR', 'ADVANCE_VENDOR', name='vendortypeenum'), nullable=False),
    sa.Column('vendor_profile', sa.Enum('BROKER', 'FLEET_OWNER', name='vendorprofileenum'), nullable=False),
    sa.Column('gst_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('gst_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pan_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('pan_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('pin_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('address_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('credit_period', sa.Integer(), nullable=False),
    sa.Column('operation_zone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='vendorstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['marketline_branches.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['marketline_cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['marketline_countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['marketline_districts.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['marketline_vendor_registrations.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['marketline_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gst_number'),
    sa.UniqueConstraint('pan_number'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_index(op.f('ix_marketline_vendors_id'), 'marketline_vendors', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_vendors_is_active'), 'marketline_vendors', ['is_active'], unique=False)
    op.create_table('marketline_vendor_agreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_vendor_agreements_id'), 'marketline_vendor_agreements', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_vendor_agreements_is_active'), 'marketline_vendor_agreements', ['is_active'], unique=False)
    op.create_table('marketline_vendor_bank_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ifsc_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('account_holder_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_marketline_vendor_bank_details_id'), 'marketline_vendor_bank_details', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_vendor_bank_details_is_active'), 'marketline_vendor_bank_details', ['is_active'], unique=False)
    op.create_table('marketline_vendor_contact_persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_marketline_vendor_contact_persons_id'), 'marketline_vendor_contact_persons', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_vendor_contact_persons_is_active'), 'marketline_vendor_contact_persons', ['is_active'], unique=False)
    op.create_table('marketline_vendor_vehicle_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['marketline_vehicle_types.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendors.id'], ),
    sa.PrimaryKeyConstraint('id', 'vendor_id', 'vehicle_type_id')
    )
    op.create_index(op.f('ix_marketline_vendor_vehicle_link_id'), 'marketline_vendor_vehicle_link', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_vendor_vehicle_link_is_active'), 'marketline_vendor_vehicle_link', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_vendor_vehicle_link_is_active'), table_name='marketline_vendor_vehicle_link')
    op.drop_index(op.f('ix_marketline_vendor_vehicle_link_id'), table_name='marketline_vendor_vehicle_link')
    op.drop_table('marketline_vendor_vehicle_link')
    op.drop_index(op.f('ix_marketline_vendor_contact_persons_is_active'), table_name='marketline_vendor_contact_persons')
    op.drop_index(op.f('ix_marketline_vendor_contact_persons_id'), table_name='marketline_vendor_contact_persons')
    op.drop_table('marketline_vendor_contact_persons')
    op.drop_index(op.f('ix_marketline_vendor_bank_details_is_active'), table_name='marketline_vendor_bank_details')
    op.drop_index(op.f('ix_marketline_vendor_bank_details_id'), table_name='marketline_vendor_bank_details')
    op.drop_table('marketline_vendor_bank_details')
    op.drop_index(op.f('ix_marketline_vendor_agreements_is_active'), table_name='marketline_vendor_agreements')
    op.drop_index(op.f('ix_marketline_vendor_agreements_id'), table_name='marketline_vendor_agreements')
    op.drop_table('marketline_vendor_agreements')
    op.drop_index(op.f('ix_marketline_vendors_is_active'), table_name='marketline_vendors')
    op.drop_index(op.f('ix_marketline_vendors_id'), table_name='marketline_vendors')
    op.drop_table('marketline_vendors')
    # ### end Alembic commands ###
