"""add doument in agreement

Revision ID: b3bb7fba1691
Revises: e8e10a0bb79f
Create Date: 2025-10-08 11:16:19.982551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3bb7fba1691'
down_revision: Union[str, Sequence[str], None] = 'e8e10a0bb79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_customer_agreements', sa.Column('agreement_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.alter_column('marketline_customers', 'gst_document',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('marketline_customers', 'pan_document',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('marketline_customers', 'address_document',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_customers', 'address_document',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('marketline_customers', 'pan_document',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('marketline_customers', 'gst_document',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('marketline_customer_agreements', 'agreement_document')
    # ### end Alembic commands ###
