"""advance payment model modification

Revision ID: bc44e7939eca
Revises: 979abb04ea66
Create Date: 2025-11-20 16:55:28.313997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc44e7939eca'
down_revision: Union[str, Sequence[str], None] = '979abb04ea66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_advance_payments', 'vendor_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_advance_payments', 'vendor_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
