"""add desc string

Revision ID: bc637c22b41f
Revises: 867711b25eed
Create Date: 2025-11-22 16:05:02.329115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'bc637c22b41f'
down_revision: Union[str, Sequence[str], None] = '867711b25eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_branches', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('marketline_branches', sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_branches', 'mobile')
    op.drop_column('marketline_branches', 'email')
    # ### end Alembic commands ###
