"""include code

Revision ID: c88967d0598b
Revises: 5987872686bc
Create Date: 2025-10-27 16:09:15.421956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c88967d0598b'
down_revision: Union[str, Sequence[str], None] = '5987872686bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_complaints', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True))
    op.create_index(op.f('ix_marketline_complaints_code'), 'marketline_complaints', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_complaints_code'), table_name='marketline_complaints')
    op.drop_column('marketline_complaints', 'code')
    # ### end Alembic commands ###
