"""Advance Payment model modification

Revision ID: ccb12be32e0e
Revises: 970ac94ddb89
Create Date: 2025-11-17 14:37:58.448490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccb12be32e0e'
down_revision: Union[str, Sequence[str], None] = '970ac94ddb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_advance_payments', 'amount',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_advance_payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
