"""add status timeline complaint

Revision ID: cf278b70c4f7
Revises: fbf48c7ba467
Create Date: 2025-10-27 13:20:01.233871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cf278b70c4f7'
down_revision: Union[str, Sequence[str], None] = 'fbf48c7ba467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_complaint_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['marketline_users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['marketline_complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_complaint_status_history_id'), 'marketline_complaint_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_complaint_status_history_is_active'), 'marketline_complaint_status_history', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_complaint_status_history_is_active'), table_name='marketline_complaint_status_history')
    op.drop_index(op.f('ix_marketline_complaint_status_history_id'), table_name='marketline_complaint_status_history')
    op.drop_table('marketline_complaint_status_history')
    # ### end Alembic commands ###
