"""model update

Revision ID: cf3395a74c2d
Revises: abf9b1d27eee
Create Date: 2025-11-06 15:45:50.992724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cf3395a74c2d'
down_revision: Union[str, Sequence[str], None] = 'abf9b1d27eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_trips', sa.Column('is_advance_given', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketline_trips', 'is_advance_given')
    # ### end Alembic commands ###
