"""trip vendor model modify

Revision ID: cfde69d81f08
Revises: 1c79457adb00
Create Date: 2025-10-31 17:33:45.601940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfde69d81f08'
down_revision: Union[str, Sequence[str], None] = '1c79457adb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_trip_status_history', 'previous_status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', name='tripstatusenum', native_enum=False, length=20),
               existing_nullable=True)
    op.alter_column('marketline_trip_status_history', 'current_status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', name='tripstatusenum', native_enum=False, length=20),
               existing_nullable=False)
    op.alter_column('marketline_trips', 'status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', name='tripstatusenum', native_enum=False, length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_trips', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', name='tripstatusenum', native_enum=False, length=20),
               type_=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               existing_nullable=True)
    op.alter_column('marketline_trip_status_history', 'current_status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', name='tripstatusenum', native_enum=False, length=20),
               type_=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               existing_nullable=False)
    op.alter_column('marketline_trip_status_history', 'previous_status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'APPROVED', 'REJECTED', 'VENDOR_ASSIGNED', 'DRIVER_ASSIGNED', 'RATE_CONFIRMED', name='tripstatusenum', native_enum=False, length=20),
               type_=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               existing_nullable=True)
    # ### end Alembic commands ###
