"""add complaint table

Revision ID: d415f8f1d8ab
Revises: 98e40f276ff0
Create Date: 2025-10-14 14:58:54.197012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd415f8f1d8ab'
down_revision: Union[str, Sequence[str], None] = '98e40f276ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('user_type', sa.Enum('CUSTOMER', 'VENDOR', name='usertypeenum'), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='complaintstatusenum'), nullable=False),
    sa.Column('subject_type', sa.Enum('BLOCK', 'OTHER', name='subjecttypeenum'), nullable=False),
    sa.Column('custom_subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('complaint_date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['marketline_customers.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_complaints_id'), 'marketline_complaints', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_complaints_is_active'), 'marketline_complaints', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_complaints_is_active'), table_name='marketline_complaints')
    op.drop_index(op.f('ix_marketline_complaints_id'), table_name='marketline_complaints')
    op.drop_table('marketline_complaints')
    # ### end Alembic commands ###
