"""Advance Payment model modification

Revision ID: d7779b09d060
Revises: 251647e1c7a4
Create Date: 2025-11-17 13:35:06.979144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7779b09d060'
down_revision: Union[str, Sequence[str], None] = '251647e1c7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_advance_payments', sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))
    op.add_column('marketline_advance_payments', sa.Column('is_paid_amount', sa.Boolean(), nullable=False))
    op.alter_column('marketline_advance_payments', 'utr_no',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_marketline_advance_payments_payment_type'), 'marketline_advance_payments', ['payment_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_advance_payments_payment_type'), table_name='marketline_advance_payments')
    op.alter_column('marketline_advance_payments', 'utr_no',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('marketline_advance_payments', 'is_paid_amount')
    op.drop_column('marketline_advance_payments', 'payment_type')
    # ### end Alembic commands ###
