"""advance payment working

Revision ID: db873655a2ee
Revises: 4a96ec48dc86
Create Date: 2025-10-10 18:54:42.407818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'db873655a2ee'
down_revision: Union[str, Sequence[str], None] = '4a96ec48dc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_advance_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('utr_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['marketline_customers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['marketline_trips.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['marketline_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_advance_payments_id'), 'marketline_advance_payments', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_advance_payments_is_active'), 'marketline_advance_payments', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_advance_payments_utr_no'), 'marketline_advance_payments', ['utr_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_advance_payments_utr_no'), table_name='marketline_advance_payments')
    op.drop_index(op.f('ix_marketline_advance_payments_is_active'), table_name='marketline_advance_payments')
    op.drop_index(op.f('ix_marketline_advance_payments_id'), table_name='marketline_advance_payments')
    op.drop_table('marketline_advance_payments')
    # ### end Alembic commands ###
