"""notification user_id column changed to user_ids and foreign key removed

Revision ID: dca5a1f04dce
Revises: 9c31d38b6207
Create Date: 2026-02-13 11:43:41.328766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dca5a1f04dce'
down_revision: Union[str, Sequence[str], None] = '9c31d38b6207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if user_ids column exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('marketline_notifications')]
    
    if 'user_ids' not in columns:
        op.add_column('marketline_notifications', sa.Column('user_ids', sa.Text(), nullable=True))
    
    # Drop foreign key constraint first, then index
    try:
        op.drop_constraint(op.f('marketline_notifications_ibfk_1'), 'marketline_notifications', type_='foreignkey')
    except:
        pass  # Constraint might not exist
    
    try:
        op.drop_index(op.f('ix_marketline_notifications_user_id'), table_name='marketline_notifications')
    except:
        pass  # Index might not exist
    
    op.drop_column('marketline_notifications', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_notifications', sa.Column('user_id', mysql.CHAR(length=32), nullable=True))
    op.create_foreign_key(op.f('marketline_notifications_ibfk_1'), 'marketline_notifications', 'marketline_users', ['user_id'], ['id'])
    op.create_index(op.f('ix_marketline_notifications_user_id'), 'marketline_notifications', ['user_id'], unique=False)
    op.drop_column('marketline_notifications', 'user_ids')
    # ### end Alembic commands ###
