"""customer update

Revision ID: e8e10a0bb79f
Revises: 3db1ecd96a4c
Create Date: 2025-10-07 19:59:16.967186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e8e10a0bb79f'
down_revision: Union[str, Sequence[str], None] = '3db1ecd96a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_customer_vehicle_link_id'), table_name='marketline_customer_vehicle_link')
    op.drop_index(op.f('ix_marketline_customer_vehicle_link_is_active'), table_name='marketline_customer_vehicle_link')
    op.drop_table('marketline_customer_vehicle_link')
    op.add_column('marketline_customers', sa.Column('payment_term', sa.Enum('ADVANCE', 'CREDIT', name='paymentterm'), nullable=True))
    op.add_column('marketline_customers', sa.Column('vehicle_type_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'marketline_customers', 'marketline_vehicle_types', ['vehicle_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketline_customers', type_='foreignkey')
    op.drop_column('marketline_customers', 'vehicle_type_id')
    op.drop_column('marketline_customers', 'payment_term')
    op.create_table('marketline_customer_vehicle_link',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('updated_by', mysql.CHAR(length=32), nullable=True),
    sa.Column('customer_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('vehicle_type_id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['marketline_customers.id'], name=op.f('marketline_customer_vehicle_link_ibfk_1')),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['marketline_vehicle_types.id'], name=op.f('marketline_customer_vehicle_link_ibfk_2')),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'vehicle_type_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_marketline_customer_vehicle_link_is_active'), 'marketline_customer_vehicle_link', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_customer_vehicle_link_id'), 'marketline_customer_vehicle_link', ['id'], unique=False)
    # ### end Alembic commands ###
