"""working on region table

Revision ID: f3b7a99e3b1e
Revises: 07180a458d2f
Create Date: 2025-09-24 17:16:00.302437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f3b7a99e3b1e'
down_revision: Union[str, Sequence[str], None] = '07180a458d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketline_regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketline_regions_id'), 'marketline_regions', ['id'], unique=False)
    op.create_index(op.f('ix_marketline_regions_is_active'), 'marketline_regions', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketline_regions_name'), 'marketline_regions', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketline_regions_name'), table_name='marketline_regions')
    op.drop_index(op.f('ix_marketline_regions_is_active'), table_name='marketline_regions')
    op.drop_index(op.f('ix_marketline_regions_id'), table_name='marketline_regions')
    op.drop_table('marketline_regions')
    # ### end Alembic commands ###
