"""add user in vendor

Revision ID: f8923e71b6cc
Revises: b29c1584c4b4
Create Date: 2025-09-26 13:07:48.809931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f8923e71b6cc'
down_revision: Union[str, Sequence[str], None] = 'b29c1584c4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketline_vendors', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'marketline_vendors', 'marketline_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketline_vendors', type_='foreignkey')
    op.drop_column('marketline_vendors', 'user_id')
    # ### end Alembic commands ###
