"""make fields to be null

Revision ID: fbf48c7ba467
Revises: 3db48b8af89d
Create Date: 2025-10-24 11:54:43.636869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbf48c7ba467'
down_revision: Union[str, Sequence[str], None] = '3db48b8af89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_targets', 'achieved_trips',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('marketline_targets', 'achieved_margin',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('marketline_targets', 'achieved_revenue',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketline_targets', 'achieved_revenue',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('marketline_targets', 'achieved_margin',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('marketline_targets', 'achieved_trips',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
